development:
  adapter: postgresql
  encoding: unicode
  database: recime_development
  pool: 5
  username: recime
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: recime_test
  pool: 5
  username: recime
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: recime_production
  pool: 5
  username: recime
  password:
